name: xson
description: A starting point for Dart libraries or applications.
version: 0.0.6+5
homepage: https://github.com/Arxing/dart-xson
author: Arxing <meiswind711108@gmail.com>
pubpage: https://pub.dev/packages/xson

environment:
  sdk: '>=2.4.0 <3.0.0'

dependencies:
  json_annotation: ^3.0.0
  dartpoet: ^1.0.0
  xfile: ^1.0.2
  named_mode: ^1.0.1

dev_dependencies:
  pedantic: ^1.7.0
  test: ^1.6.0

  build_runner: ^1.6.7
  json_serializable: ^3.2.2
