name: xson
description: A starting point for Dart libraries or applications.
version: 0.0.8
homepage: https://github.com/Arxing/dart-xson
author: Arxing <meiswind711108@gmail.com>
pubpage: https://pub.dev/packages/xson

environment:
  sdk: '>=2.4.0 <3.0.0'

dependencies:
  dartpoet: ^1.0.3+2
  xfile: ^1.0.2
  named_mode: ^1.0.1

dev_dependencies:
  build_runner: ^1.6.7
