name: xson_utils
description: A starting point for Dart libraries or applications.
version: 0.1.0
homepage: https://github.com/Arxing/dart-xson
author: Arxing <meiswind711108@gmail.com>
pubpage: https://pub.dev/packages/xson

environment:
  sdk: '>=2.4.0 <3.0.0'

#dependencies:
#  path: ^1.6.0

#dev_dependencies:
#  pedantic: ^1.7.0
#  test: ^1.6.0
